version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/data:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./../src/backend_php:/opt/jet/backend/
    - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
  php:
    stdin_open: true
    build: ./php
    #image: php:7.1-fpm
    volumes:
    - ./../src/backend_php:/opt/jet/backend
    links:
      - db